#!/bin/bash

sed -e "s/NSOLRES/$NUM_OF_SOLUTE_RESIDUES/g" < relax07.tin > relax07.in || exit 1

pmemd.cuda -O -i relax07.in -p ../$PEQUI_TOP -c ../relax06/relax06.rst7 -ref ../relax06/relax06.rst7 -o relax07.out -r relax07.rst7 -x relax07.btraj


