#!/bin/bash

sed -e "s/NSOLRES/$NUM_OF_SOLUTE_RESIDUES/g" < relax06.tin > relax06.in || exit 1

pmemd.cuda -O -i relax06.in -p ../$PEQUI_TOP -c ../relax05/relax05.rst7 -ref ../relax05/relax05.rst7 -o relax06.out -r relax06.rst7 -x relax06.btraj


