#!/bin/bash

sed -e "s/NSOLRES/$NUM_OF_SOLUTE_RESIDUES/g" < relax09.tin > relax09.in || exit 1

pmemd.cuda -O -i relax09.in -p ../$PEQUI_TOP -c ../relax08/relax08.rst7 -ref ../relax08/relax08.rst7 -o relax09.out -r relax09.rst7 -x relax09.btraj


