#!/bin/bash

sed -e "s/NSOLRES/$NUM_OF_SOLUTE_RESIDUES/g" < relax02.tin > relax02.in || exit 1

pmemd.cuda -O -i relax02.in -p ../$PEQUI_TOP -c ../relax01/relax01.rst7 -ref ../$PEQUI_CRD -o relax02.out -r relax02.rst7 -x relax02.btraj


